In [4]:
import numpy as np
import pandas as pd
from random import randrange
from neupy import algorithms

WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
c:\users\xxx\envs\mita\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [2]:
dataset_norma = pd.read_csv('output/dataset-normalisasi.csv')


In [5]:
train_data = dataset_norma.loc[:, ~dataset_norma.columns.isin(['ID'])]

In [16]:
X = train_data.iloc[:, :-1].to_numpy()
Y = train_data.iloc[:, -1].to_numpy()

In [30]:
np.unique(Y).size

2

In [48]:
lvqnet = algorithms.LVQ2(n_inputs=X.shape[1], n_classes=np.unique(Y).size, verbose=True)
lvqnet.train(X, Y, epochs=30)
lvqnet.errors

--Return--
None
> <ipython-input-48-774891484f35>(1)<module>()
----> 1 import pdb; pdb.set_trace();
      2 lvqnet = algorithms.LVQ2(n_inputs=X.shape[1], n_classes=np.unique(Y).size, verbose=True)
      3 lvqnet.train(X, Y, epochs=30)
      4 lvqnet.errors

ipdb> c

Main information

[ALGORITHM] LVQ2

[OPTION] verbose = True
[OPTION] epoch_end_signal = None
[OPTION] show_epoch = 1
[OPTION] shuffle_data = False
[OPTION] step = 0.1
[OPTION] train_end_signal = None
[OPTION] minstep = 1e-05
[OPTION] n_classes = 2
[OPTION] n_inputs = 19
[OPTION] n_subclasses = None
[OPTION] n_updates_to_stepdrop = None
[OPTION] prototypes_per_class = None
[OPTION] weight = None
[OPTION] epsilon = 0.1


Start training

[TRAINING DATA] shapes: (154, 19)
[TRAINING] Total epochs: 30

---------------------------------------------------------
|    Epoch    |  Train err  |  Valid err  |    Time     |
---------------------------------------------------------
|           1 |     0.16234 |           - |      114 ms |

[array([0.16233766]),
 array([0.18831169]),
 array([0.17532468]),
 array([0.16883117]),
 array([0.17532468]),
 array([0.18181818]),
 array([0.16883117]),
 array([0.16233766]),
 array([0.17532468]),
 array([0.18181818]),
 array([0.16233766]),
 array([0.17532468]),
 array([0.18181818]),
 array([0.18181818]),
 array([0.16233766]),
 array([0.16883117]),
 array([0.16883117]),
 array([0.17532468]),
 array([0.16883117]),
 array([0.16883117]),
 array([0.16233766]),
 array([0.16883117]),
 array([0.16883117]),
 array([0.17532468]),
 array([0.16883117]),
 array([0.16883117]),
 array([0.16233766]),
 array([0.16883117]),
 array([0.16883117]),
 array([0.17532468])]