In [34]:
import numpy as np
import pandas as pd
from random import randrange
from neupy import algorithms
from sklearn.model_selection import train_test_split
np.random.seed = 0

TypeError: 'int' object is not callable

In [17]:
dataset_norma = pd.read_csv('output/dataset-normalisasi.csv')
X = dataset_norma.loc[:, ~dataset_norma.columns.isin(['ID', 'CLASS'])]
y = dataset_normanorma.loc[:, dataset_norma.columns.isin(['CLASS'])]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=data_output, random_state=0)


19

In [33]:
lvqnet = algorithms.LVQ2(n_inputs=X.shape[1], n_classes=np.unique(y).size, verbose=True)
lvqnet.train(X_train, y_train, epochs=30)
lvqnet.errors


Main information

[ALGORITHM] LVQ2

[OPTION] verbose = True
[OPTION] epoch_end_signal = None
[OPTION] show_epoch = 1
[OPTION] shuffle_data = False
[OPTION] step = 0.1
[OPTION] train_end_signal = None
[OPTION] minstep = 1e-05
[OPTION] n_classes = 2
[OPTION] n_inputs = 19
[OPTION] n_subclasses = None
[OPTION] n_updates_to_stepdrop = None
[OPTION] prototypes_per_class = None
[OPTION] weight = None
[OPTION] epsilon = 0.1


Start training

[TRAINING DATA] shapes: (138, 19)
[TRAINING] Total epochs: 30

---------------------------------------------------------
|    Epoch    |  Train err  |  Valid err  |    Time     |
---------------------------------------------------------
|           1 |     0.23913 |           - |       60 ms |
|           2 |     0.21014 |           - |       67 ms |
|           3 |     0.18841 |           - |      101 ms |
|           4 |     0.19565 |           - |       64 ms |
|           5 |     0.19565 |           - |       61 ms |
|           6 |     0.19565 |    

[array([0.23913043]),
 array([0.21014493]),
 array([0.1884058]),
 array([0.19565217]),
 array([0.19565217]),
 array([0.19565217]),
 array([0.1884058]),
 array([0.1884058]),
 array([0.19565217]),
 array([0.1884058]),
 array([0.19565217]),
 array([0.20289855]),
 array([0.19565217]),
 array([0.2173913]),
 array([0.18115942]),
 array([0.1884058]),
 array([0.18115942]),
 array([0.19565217]),
 array([0.1884058]),
 array([0.18115942]),
 array([0.1884058]),
 array([0.21014493]),
 array([0.20289855]),
 array([0.19565217]),
 array([0.1884058]),
 array([0.21014493]),
 array([0.19565217]),
 array([0.1884058]),
 array([0.19565217]),
 array([0.19565217])]